const ions=[
{name:"acetate",formula:"C₂H₃O₂⁻",image:"acetate.png"},{name:"carbonate",formula:"CO₃²⁻",image:"carbonate.png"},{name:"hydrogen carbonate",formula:"HCO₃⁻",image:"bicarbonate.png",aliases:["bicarbonate"]},{name:"hydroxide",formula:"OH⁻",image:"hydroxide.png"},{name:"nitrate",formula:"NO₃⁻",image:"nitrate.png"},{name:"nitrite",formula:"NO₂⁻",image:"nitrite.png"},{name:"chromate",formula:"CrO₄²⁻",image:"chromate.png"},{name:"dichromate",formula:"Cr₂O₇²⁻",image:"dichromate.png"},{name:"phosphate",formula:"PO₄³⁻",image:"phosphate.png"},{name:"hydrogen phosphate",formula:"HPO₄²⁻",image:"hydrogen_phosphate.png"},{name:"ammonium",formula:"NH₄⁺",image:"ammonium.png"},{name:"hypochlorite",formula:"ClO⁻",image:"hypochlorite.png"},{name:"chlorite",formula:"ClO₂⁻",image:"chlorite.png"},{name:"chlorate",formula:"ClO₃⁻",image:"chlorate.png"},{name:"perchlorate",formula:"ClO₄⁻",image:"perchlorate.png"},{name:"permanganate",formula:"MnO₄⁻",image:"permanganate.png"},{name:"sulfate",formula:"SO₄²⁻",image:"sulfate.png"},{name:"sulfite",formula:"SO₃²⁻",image:"sulfite.png"},{name:"hydrogen sulfite",formula:"HSO₃⁻",image:"bisulfite.png",aliases:["bisulfite"]},{name:"hydrogen sulfate",formula:"HSO₄⁻",image:"bisulfate.png",aliases:["bisulfate"]},{name:"peroxide",formula:"O₂²⁻",image:"peroxide.png"},{name:"cyanide",formula:"CN⁻",image:"cyanide.png"}];
const KEY="pai-passport-v2",NAME_KEY="pai-learner-name",BEST_KEY="pai-flight-best",XP_KEY="pai-xp-v1",XP_AWARDS_KEY="pai-xp-awards-v1";
let currentMode="",roundIndex=0,currentSet=[],locked=false,flight=null;
// Persistent XP rewards practice; Passport mastery alone controls certificate eligibility.
let xp=Math.max(0,Number(localStorage.getItem(XP_KEY)||0));
let xpAwards=(()=>{try{return JSON.parse(localStorage.getItem(XP_AWARDS_KEY)||"{}")||{}}catch(e){return {}}})();
const XP_STEP=250;
const XP_TITLES=["Ion Rookie","Charge Chaser","Formula Finder","Ion Wrangler","Polyatomic Pro"];
function xpLevel(){return Math.floor(xp/XP_STEP)+1}
function xpTitle(level=xpLevel()){return XP_TITLES[Math.min(level-1,XP_TITLES.length-1)]||("Polyatomic Pro")}
function renderXP(){const level=xpLevel(),base=(level-1)*XP_STEP,next=level*XP_STEP,within=xp-base;const a=qs("xpLevel"),b=qs("xpTotal"),c=qs("xpFill"),d=qs("xpNext");if(a)a.textContent=`Level ${level} — ${xpTitle(level)}`;if(b)b.textContent=`${xp.toLocaleString()} XP`;if(c)c.style.width=`${Math.min(100,within/XP_STEP*100)}%`;if(d)d.textContent=`${(next-xp).toLocaleString()} XP to Level ${level+1}`}
function awardXP(amount,label="Practice"){amount=Math.max(0,Math.round(amount));if(!amount)return;xp+=amount;localStorage.setItem(XP_KEY,String(xp));renderXP();const pop=qs("xpPop");if(pop){pop.textContent=`+${amount} XP • ${label}`;pop.classList.add("show");clearTimeout(awardXP._t);awardXP._t=setTimeout(()=>pop.classList.remove("show"),1300)}}
function oneTimeXP(key,amount,label){if(xpAwards[key])return;xpAwards[key]=true;localStorage.setItem(XP_AWARDS_KEY,JSON.stringify(xpAwards));awardXP(amount,label)}

const qs=id=>document.getElementById(id);const shuffle=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
function blankPassport(){const p={};ions.forEach(i=>p[i.name]={formula:0,name:0});return p}
function loadPassport(){try{const raw=JSON.parse(localStorage.getItem(KEY));const p=blankPassport();if(raw)ions.forEach(i=>{p[i.name].formula=Math.min(5,Math.max(0,raw[i.name]?.formula||0));p[i.name].name=Math.min(5,Math.max(0,raw[i.name]?.name||0))});return p}catch(e){return blankPassport()}}
let passport=loadPassport();
function savePassport(){localStorage.setItem(KEY,JSON.stringify(passport));updateMastery();renderPassport();if(isMastered())completeAcademyActivity()}
function stamp(ion,mode){if(mode!=="formula"&&mode!=="name")return;if(passport[ion.name][mode]<5){passport[ion.name][mode]++;savePassport()}}
function totals(){return ions.reduce((a,i)=>({formula:a.formula+passport[i.name].formula,name:a.name+passport[i.name].name}),{formula:0,name:0})}
function isMastered(){const t=totals();return t.formula===110&&t.name===110}
function startFlashcard(){startMode("flashcard")}function startFormulaMode(){startMode("formula")}function startNameMode(){startMode("name")}
function startMode(mode){stopFlight();currentMode=mode;roundIndex=0;currentSet=shuffle(ions);locked=false;qs("main-menu").style.display="none";qs("labReturn").style.display="block";qs("game-area").style.display="block";qs("progressWrap").style.display="block";feedback("");updateProgress();nextCard()}
function feedback(msg,good=false){const el=qs("feedback");el.textContent=msg;el.className="feedback"+(good?" good":"")}
function nextCard(){locked=false;if(roundIndex>=currentSet.length){finishRound();return}const ion=currentSet[roundIndex],area=qs("game-area");let prompt=currentMode==="flashcard"?ion.name:currentMode==="name"?ion.formula:`What is the formula for ${ion.name}?`;area.innerHTML=`<div class="game-layout"><div class="answer-zone"><div class="question">${prompt}</div><div id="controls"></div></div><div id="visual" class="image-container"><div class="image-placeholder">Ion structure appears after reveal/correct answer</div></div></div>`;const c=qs("controls");if(currentMode==="flashcard"){c.innerHTML=`<button class="primary" onclick="revealFlashcard()">Reveal formula & structure</button><button class="secondary" onclick="advance()">Next ion</button>`}else if(currentMode==="name"){c.innerHTML=`<input class="answer-input" id="nameInput" placeholder="Enter ion name" autocomplete="off"><br><button class="primary" onclick="checkNameAnswer()">Submit</button>`;qs("nameInput").addEventListener("keydown",e=>{if(e.key==="Enter")checkNameAnswer()});qs("nameInput").focus()}else{renderFormulaChoices(c,ion,(choice,btn,box)=>checkFormula(choice,btn,box))}updateProgress()}
function renderFormulaChoices(c,ion,handler){const box=document.createElement("div");box.className="formula-buttons";shuffle([ion.formula,...shuffle(ions.filter(x=>x.formula!==ion.formula)).slice(0,3).map(x=>x.formula)]).forEach(choice=>{const b=document.createElement("button");b.className="answer-btn";b.textContent=choice;b.onclick=()=>handler(choice,b,box);box.appendChild(b)});c.appendChild(box)}
function showIon(ion,withFormula=false){qs("visual").innerHTML=`<div><img src="${ion.image}" alt="Structure representation for ${ion.name}">${withFormula?`<div style="font-size:1.45rem;font-weight:800;margin-top:8px">${ion.formula}</div>`:""}</div>`}
function revealFlashcard(){showIon(currentSet[roundIndex],true);feedback(currentSet[roundIndex].name+" — "+currentSet[roundIndex].formula,true)}
function advance(){roundIndex++;feedback("");updateProgress();nextCard()}
function validName(input,ion){const v=input.trim().toLowerCase();return v===ion.name.toLowerCase()||(ion.aliases||[]).some(a=>v===a)}
function checkNameAnswer(){if(locked)return;const input=qs("nameInput"),ion=currentSet[roundIndex];if(validName(input.value,ion)){locked=true;stamp(ion,"name");awardXP(5,"Passport recall");sfx("correct");feedback(`Correct! Passport: ${passport[ion.name].name}/5`,true);showIon(ion,true);setTimeout(advance,900)}else{sfx("wrong");feedback("Not quite — try again.");input.select()}}
function checkFormula(choice,btn,box){if(locked)return;const ion=currentSet[roundIndex];if(choice===ion.formula){locked=true;stamp(ion,"formula");awardXP(5,"Passport recall");btn.classList.add("correct");box.querySelectorAll("button").forEach(b=>b.disabled=true);sfx("correct");feedback(`Correct! Passport: ${passport[ion.name].formula}/5`,true);showIon(ion);setTimeout(advance,900)}else{sfx("wrong");btn.classList.add("incorrect");btn.disabled=true;feedback("Not quite — try another formula.")}}
function finishRound(){sfx("complete");qs("progressFill").style.width="100%";qs("progressCount").textContent=`22 / 22`;const mastered=isMastered();qs("game-area").innerHTML=`<div class="certificate"><h2>${mastered?"Passport Complete!":"Round Complete!"}</h2><p>${mastered?"You earned all 220 Passport stamps — five successful recalls for every ion in both directions.":"Your correct recalls have been added to your Passport. You can stop now or keep building mastery later."}</p>${mastered?`<button class="primary" onclick="downloadCertificate()">Download Mastery Credential</button>`:""}<button class="primary" onclick="continueCurrentMode()">I want to continue in this mode</button><button class="secondary" onclick="returnHome()">Return to Training Lab</button>${mastered?`<button class="primary" onclick="returnToAcademy()">Return to Academy</button>`:""}</div>`}
function continueCurrentMode(){if(currentMode==="flashcard")startFlashcard();else if(currentMode==="formula")startFormulaMode();else if(currentMode==="name")startNameMode();}
function updateProgress(){qs("progressFill").style.width=`${Math.min(roundIndex/ions.length*100,100)}%`;qs("progressCount").textContent=`${Math.min(roundIndex,ions.length)} / ${ions.length}`}
function updateMastery(){const t=totals();qs("formulaText").textContent=`${t.formula} / 110`;qs("nameText").textContent=`${t.name} / 110`;qs("formulaMini").style.width=`${t.formula/110*100}%`;qs("nameMini").style.width=`${t.name/110*100}%`}
function renderPassport(){const g=qs("passportGrid");g.innerHTML=ions.map(i=>`<div class="passport-row"><strong>${title(i.name)}</strong><span class="stamp ${passport[i.name].formula===5?'done':''}" title="Name to Formula">N→F ${passport[i.name].formula}/5</span><span class="stamp ${passport[i.name].name===5?'done':''}" title="Formula to Name">F→N ${passport[i.name].name}/5</span></div>`).join("")}
function togglePassport(){const g=qs("passportGrid");g.style.display=g.style.display==="none"?"grid":"none"}
function title(s){return s.replace(/\b\w/g,c=>c.toUpperCase())}
function startFlight(){stopFlight();currentMode="flight";qs("main-menu").style.display="none";qs("labReturn").style.display="block";qs("progressWrap").style.display="none";qs("game-area").style.display="block";feedback("");flight={altitude:72,distance:0,correct:0,attempts:0,streak:0,bestStreak:0,active:true,ion:null,direction:null,last:performance.now(),level:1,shield:0,boostUntil:0,nextPower:650+Math.random()*550,power:null};qs("game-area").innerHTML=`<div class="flight-hud"><span>Distance: <b id="flightDistance">0 m</b></span><span>Correct: <b id="flightCorrect">0</b></span><span>Streak: <b id="flightStreak">0</b></span><span>Level: <b id="flightLevel">1</b></span></div><div class="sky"><div id="levelBanner" class="level-banner"></div><div id="powerup" class="powerup"></div><span class="cloud c1">☁</span><span class="cloud c2">☁</span><div class="shore"></div><div id="plane" class="plane">➤</div></div><div class="altitude"><div id="altitudeFill"></div></div><div id="flightQuestion"></div>`;nextFlightQuestion();flight.timer=setInterval(flightTick,100)}
function nextFlightQuestion(){if(!flight?.active)return;let ion=ions[Math.floor(Math.random()*ions.length)];if(flight.ion&&ions.length>1)while(ion===flight.ion)ion=ions[Math.floor(Math.random()*ions.length)];flight.ion=ion;flight.direction=Math.random()<.5?"name":"formula";const q=qs("flightQuestion");if(flight.direction==="name"){q.innerHTML=`<div class="question">${ion.formula}</div><div style="max-width:520px;margin:auto;text-align:center"><input class="answer-input" id="flightInput" placeholder="Type the ion name" autocomplete="off"><button class="primary" onclick="submitFlightName()">Submit</button></div>`;qs("flightInput").addEventListener("keydown",e=>{if(e.key==="Enter")submitFlightName()});qs("flightInput").focus()}else{q.innerHTML=`<div class="question">What is the formula for ${ion.name}?</div><div id="flightChoices" class="formula-buttons"></div>`;renderFormulaChoices(qs("flightChoices"),ion,(choice)=>submitFlightFormula(choice))}}
function flightLevel(){return Math.floor(flight.distance/1000)+1}
function flightTick(){if(!flight?.active)return;const lvl=flightLevel();if(lvl!==flight.level){flight.level=lvl;awardXP(25,`Reached Flight Level ${lvl}`);qs("flightLevel").textContent=lvl;const b=qs("levelBanner");b.textContent=`LEVEL ${lvl} — ${Math.floor(flight.distance/1000)*1000} m!`;b.classList.add("show");sfx("level");setTimeout(()=>b?.classList.remove("show"),1200)}const gravity=.28+Math.min(.34,(lvl-1)*.055);flight.altitude-=gravity;const tailwind=performance.now()<flight.boostUntil;flight.distance+=tailwind?3.4:2;if(!flight.power&&flight.distance>=flight.nextPower)spawnPowerup();qs("flightDistance").textContent=`${Math.floor(flight.distance)} m`;qs("altitudeFill").style.width=`${Math.max(0,flight.altitude)}%`;qs("plane").style.bottom=`${22+Math.max(0,flight.altitude)*.58}%`;qs("plane").style.left=`${14+Math.min(65,flight.distance/55)}%`;if(flight.altitude<=0)endFlight()}
function spawnPowerup(){const kinds=[{id:"updraft",icon:"☁️",label:"UPDRAFT"},{id:"shield",icon:"🛡️",label:"SHIELD"},{id:"tailwind",icon:"⚡",label:"TAILWIND"}];flight.power=kinds[Math.floor(Math.random()*kinds.length)];const p=qs("powerup");p.innerHTML=`<span>${flight.power.icon}</span><small>${flight.power.label}<br>Answer correctly to collect!</small>`;p.classList.add("show")}
function collectPowerup(){if(!flight.power)return;sfx("power");const kind=flight.power.id;if(kind==="updraft")flight.altitude=Math.min(100,flight.altitude+24);if(kind==="shield")flight.shield=1;if(kind==="tailwind")flight.boostUntil=performance.now()+7000;feedback(`${flight.power.label} collected!`,true);flight.power=null;flight.nextPower=flight.distance+650+Math.random()*650;qs("powerup")?.classList.remove("show")}
function flightAnswer(ok){if(!flight?.active)return;flight.attempts++;const lvl=flightLevel();if(ok){sfx("correct");flight.correct++;awardXP(3,"Ion Flight");flight.streak++;flight.bestStreak=Math.max(flight.bestStreak,flight.streak);flight.altitude=Math.min(100,flight.altitude+Math.max(8,13-(lvl-1)*.7));flight.distance+=performance.now()<flight.boostUntil?40:24;if(flight.power)collectPowerup();else feedback("Correct — lift!",true);setTimeout(nextFlightQuestion,180)}else{sfx("wrong");flight.streak=0;const damage=Math.min(24,7+(lvl-1)*3);if(flight.shield){flight.shield=0;feedback("Shield absorbed the turbulence!");}else{flight.altitude=Math.max(0,flight.altitude-damage);feedback(`Not quite — turbulence! (${damage} altitude)`);qs("plane")?.classList.add("hit");setTimeout(()=>qs("plane")?.classList.remove("hit"),300)}}qs("flightCorrect").textContent=flight.correct;qs("flightStreak").textContent=flight.streak}
function submitFlightName(){const input=qs("flightInput");if(!input)return;const ok=validName(input.value,flight.ion);flightAnswer(ok);if(!ok){input.select();input.focus()}}
function submitFlightFormula(choice){const ok=choice===flight.ion.formula;flightAnswer(ok);if(!ok)setTimeout(nextFlightQuestion,260)}
function endFlight(){if(!flight?.active)return;sfx("land");flight.active=false;clearInterval(flight.timer);qs("plane")?.classList.add("crash");const accuracy=flight.attempts?Math.round(flight.correct/flight.attempts*100):0,best=Math.max(Number(localStorage.getItem(BEST_KEY)||0),Math.floor(flight.distance));localStorage.setItem(BEST_KEY,best);const flightBonus=Math.max(0,Math.round((accuracy>=90?25:accuracy>=75?10:0)+(flight.correct>=20?15:0)));if(flightBonus)awardXP(flightBonus,"Flight bonus");setTimeout(()=>{qs("game-area").innerHTML=`<div class="flight-result"><h2>Flight Complete</h2><p>Your paper airplane touched down.</p><div class="statline"><span>${Math.floor(flight.distance)} m</span><span>${flight.correct} correct</span><span>${accuracy}% accuracy</span><span>Best streak ${flight.bestStreak}</span></div><p>Personal best: <strong>${best} m</strong></p><button class="primary" onclick="startFlight()">I want to continue in this mode</button><button class="secondary" onclick="returnHome()">Return to Training Lab</button></div>`;feedback("")},500)}
function stopFlight(){if(flight?.timer)clearInterval(flight.timer);flight=null}
function completeAcademyActivity(){try{localStorage.setItem("nomenclature-polyatomic-mastered","true")}catch(e){}}
function returnHome(){stopFlight();qs("labReturn").style.display="none";qs("main-menu").style.display="block";qs("game-area").style.display="none";qs("progressWrap").style.display="none";feedback("");updateMastery();renderPassport()}
function returnToAcademy(){location.href="../index.html"}
function downloadCertificate(){const name=qs("learnerName").value.trim()||"Student";if(!isMastered()){alert("Complete all Passport stamps to unlock the certificate.");return}if(!window.jspdf){window.print();return}const {jsPDF}=window.jspdf,doc=new jsPDF();doc.setFontSize(24);doc.text("Mastery Credential",105,45,{align:"center"});doc.setFontSize(16);doc.text(`This certifies that ${name}`,105,68,{align:"center"});doc.text("has demonstrated mastery of the",105,80,{align:"center"});doc.setFontSize(20);doc.text("Polyatomic Ion Training Lab",105,96,{align:"center"});doc.setFontSize(13);doc.text("5 successful recalls of every ion in both directions",105,112,{align:"center"});doc.text(`Completed ${new Date().toLocaleDateString()}`,105,124,{align:"center"});doc.save(`Polyatomic_Ion_Mastery_${name.replace(/\s+/g,"_")}.pdf`)}
renderXP();qs("learnerName").value=localStorage.getItem(NAME_KEY)||"";qs("learnerName").addEventListener("input",e=>localStorage.setItem(NAME_KEY,e.target.value));updateMastery();renderPassport();if(isMastered())completeAcademyActivity();

/* Gentle, self-contained audio layer. No external audio files are required. */
const AUDIO_PREF_KEY="pai-audio-prefs-v1";
let audioPrefs=(()=>{try{return Object.assign({music:true,sfx:true},JSON.parse(localStorage.getItem(AUDIO_PREF_KEY)||"{}"))}catch(e){return {music:true,sfx:true}}})();
let audioCtx=null,musicTimer=null,musicStep=0;
function ensureAudio(){if(!audioCtx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audioCtx=new C()}if(audioCtx.state==="suspended")audioCtx.resume();return audioCtx}
function tone(freq,duration=.12,volume=.025,type="sine",delay=0){const c=ensureAudio();if(!c)return;const o=c.createOscillator(),g=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.018);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(c.destination);o.start(t);o.stop(t+duration+.03)}
function sfx(kind){if(!audioPrefs.sfx)return;if(kind==="correct"){tone(523,.10,.026,"sine");tone(659,.13,.022,"sine",.07)}else if(kind==="wrong"){tone(220,.13,.018,"triangle");tone(185,.16,.015,"triangle",.07)}else if(kind==="level"){tone(523,.11,.025,"sine");tone(659,.11,.023,"sine",.09);tone(784,.18,.022,"sine",.18)}else if(kind==="power"){tone(660,.09,.024,"sine");tone(880,.11,.022,"sine",.07);tone(1047,.17,.019,"sine",.14)}else if(kind==="land"){tone(330,.14,.018,"triangle");tone(247,.22,.014,"triangle",.10)}else if(kind==="complete"){tone(523,.10,.022,"sine");tone(659,.10,.021,"sine",.08);tone(784,.20,.020,"sine",.16)}}
function musicPulse(){if(!audioPrefs.music||document.hidden)return;const flightMode=currentMode==="flight"&&flight?.active;const calm=[196,246.94,293.66,246.94,220,261.63,329.63,261.63],air=[220,277.18,329.63,277.18,246.94,293.66,369.99,293.66],seq=flightMode?air:calm,f=seq[musicStep++%seq.length];tone(f,flightMode?.48:.62,flightMode?.008:.006,"sine");if(musicStep%4===1)tone(f/2,.75,.0035,"sine")}
function startMusic(){if(musicTimer||!audioPrefs.music)return;ensureAudio();musicPulse();musicTimer=setInterval(musicPulse,720)}
function stopMusic(){if(musicTimer){clearInterval(musicTimer);musicTimer=null}}
function saveAudioPrefs(){localStorage.setItem(AUDIO_PREF_KEY,JSON.stringify(audioPrefs));updateAudioButtons()}
function updateAudioButtons(){const m=qs("musicToggle"),e=qs("sfxToggle");if(m){m.textContent=`♫ Music: ${audioPrefs.music?"On":"Off"}`;m.classList.toggle("off",!audioPrefs.music)}if(e){e.textContent=`🔊 Effects: ${audioPrefs.sfx?"On":"Off"}`;e.classList.toggle("off",!audioPrefs.sfx)}}
function toggleMusic(){audioPrefs.music=!audioPrefs.music;saveAudioPrefs();if(audioPrefs.music)startMusic();else stopMusic()}
function toggleSfx(){audioPrefs.sfx=!audioPrefs.sfx;saveAudioPrefs();if(audioPrefs.sfx)sfx("correct")}
// Audio begins only after a user gesture, as required by modern browsers.
document.addEventListener("pointerdown",()=>{if(audioPrefs.music)startMusic();else ensureAudio()},{once:true});
updateAudioButtons();

/* Ion Capture — visual Name → Formula recognition challenge. */
let capture=null;
function startCapture(){
  stopFlight(); stopCapture(); currentMode="capture";
  qs("main-menu").style.display="none"; qs("labReturn").style.display="block";
  qs("progressWrap").style.display="none"; qs("game-area").style.display="block"; feedback("");
  capture={remaining:shuffle(ions),target:null,correct:0,attempts:0,start:performance.now(),active:true,paused:false,freezeUntil:0,floaters:new Map(),raf:null};
  qs("game-area").innerHTML=`<div class="capture-target"><small>CAPTURE THIS ION</small><strong id="captureName"></strong></div><div class="capture-stats"><span>Contained: <b id="captureCount">0 / ${ions.length}</b></span><span>Accuracy: <b id="captureAccuracy">100%</b></span></div><div class="capture-motion"><button id="capturePause" class="secondary" type="button">Pause Motion</button></div><div class="capture-wrap"><div id="captureField" class="capture-field" aria-label="Floating ion formulas"></div><aside class="containment"><h3>Containment Cells</h3><div id="cageGrid" class="cage-grid"></div></aside></div>`;
  const grid=qs("cageGrid"); ions.forEach((ion,i)=>{const c=document.createElement("div");c.className="cage";c.id=`cage-${i}`;c.innerHTML=`<span>${title(ion.name)}</span><b>—</b>`;grid.appendChild(c)});
  const field=qs("captureField");
  requestAnimationFrame(()=>{
    const W=Math.max(280,field.clientWidth),H=Math.max(260,field.clientHeight);
    capture.remaining.forEach((ion,i)=>{const b=document.createElement("button");b.type="button";b.className=`ion-floater ${["tone-blue","tone-green","tone-yellow","tone-pink"][i%4]}`;b.textContent=ion.formula;b.setAttribute("aria-label",`Formula ${ion.formula}`);const x=8+Math.random()*Math.max(10,W-115),y=8+Math.random()*Math.max(10,H-70),a=Math.random()*Math.PI*2,s=.09+Math.random()*.07;const obj={ion,el:b,x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,index:ions.indexOf(ion)};capture.floaters.set(ion.name,obj);b.addEventListener("click",()=>captureChoice(obj));field.appendChild(b)});
    chooseCaptureTarget(); let last=performance.now();
    function animate(now){if(!capture?.active)return;const dt=Math.min(32,now-last);last=now;const w=field.clientWidth,h=field.clientHeight;const movers=[...capture.floaters.values()].filter(o=>o.el.isConnected);if(!capture.paused && now>=capture.freezeUntil){for(let i=0;i<movers.length;i++){for(let j=i+1;j<movers.length;j++){const a=movers[i],b=movers[j],dx=(a.x-b.x),dy=(a.y-b.y),d2=dx*dx+dy*dy;if(d2<12500&&d2>1){const d=Math.sqrt(d2),push=(112-d)*0.000018;if(push>0){a.vx+=dx/d*push;a.vy+=dy/d*push;b.vx-=dx/d*push;b.vy-=dy/d*push}}}}movers.forEach(o=>{const speedBoost=1+Math.floor(capture.correct/4)*0.07;o.x+=o.vx*dt*speedBoost;o.y+=o.vy*dt*speedBoost;const bw=o.el.offsetWidth||100,bh=o.el.offsetHeight||60;const margin=8;if(o.x<margin){o.x=margin;o.vx=Math.abs(o.vx)*.92}if(o.x+bw>w-margin){o.x=Math.max(margin,w-bw-margin);o.vx=-Math.abs(o.vx)*.92}if(o.y<margin){o.y=margin;o.vy=Math.abs(o.vy)*.92}if(o.y+bh>h-margin){o.y=Math.max(margin,h-bh-margin);o.vy=-Math.abs(o.vy)*.92}const speed=Math.hypot(o.vx,o.vy),max=.17;if(speed>max){o.vx=o.vx/speed*max;o.vy=o.vy/speed*max}})}movers.forEach(o=>o.el.style.transform=`translate(${o.x}px,${o.y}px)`);capture.raf=requestAnimationFrame(animate)}
    capture.raf=requestAnimationFrame(animate);
    const pauseBtn=qs("capturePause"); pauseBtn.addEventListener("click",()=>{capture.paused=!capture.paused;pauseBtn.textContent=capture.paused?"Resume Motion":"Pause Motion";feedback(capture.paused?"Motion paused — you can still select formulas.":"Motion resumed.",true)});
  });
}
function chooseCaptureTarget(){if(!capture?.active)return;if(!capture.remaining.length){finishCapture();return}capture.target=capture.remaining[Math.floor(Math.random()*capture.remaining.length)];qs("captureName").textContent=title(capture.target.name)}
function captureChoice(obj){if(!capture?.active||!capture.target)return;capture.attempts++;if(obj.ion===capture.target){capture.correct++;awardXP(4,"Ion Capture");sfx("power");obj.el.classList.add("captured");setTimeout(()=>obj.el.remove(),220);capture.floaters.delete(obj.ion.name);capture.remaining=capture.remaining.filter(i=>i!==obj.ion);const cage=qs(`cage-${obj.index}`);cage.classList.add("filled");cage.innerHTML=`<span>${title(obj.ion.name)}</span><b>${obj.ion.formula}</b>`;feedback(`${title(obj.ion.name)} contained!`,true);qs("captureCount").textContent=`${capture.correct} / ${ions.length}`;updateCaptureAccuracy();setTimeout(chooseCaptureTarget,260)}else{sfx("wrong");capture.freezeUntil=performance.now()+700;obj.el.classList.remove("wrong");void obj.el.offsetWidth;obj.el.classList.add("wrong");feedback(`That is ${obj.ion.formula}. Keep looking for ${title(capture.target.name)}.`);updateCaptureAccuracy()}}
function updateCaptureAccuracy(){const pct=capture.attempts?Math.round(capture.correct/capture.attempts*100):100;qs("captureAccuracy").textContent=`${pct}%`}
function finishCapture(){if(!capture?.active)return;capture.active=false;if(capture.raf)cancelAnimationFrame(capture.raf);sfx("complete");const secs=Math.round((performance.now()-capture.start)/1000),accuracy=capture.attempts?Math.round(capture.correct/capture.attempts*100):100;const captureBonus=20+(accuracy===100?30:accuracy>=90?20:accuracy>=80?10:0);awardXP(captureBonus,"Capture completion");qs("game-area").innerHTML=`<div class="capture-complete"><h2>All Ions Contained!</h2><p>You captured all 22 polyatomic ions.</p><div class="statline"><span>${secs} s</span><span>${accuracy}% accuracy</span><span>${capture.attempts} selections</span></div><button class="primary" onclick="startCapture()">I want to continue in this mode</button><button class="secondary" onclick="returnHome()">Return to Training Lab</button></div>`;feedback("")}
function stopCapture(){if(capture?.raf)cancelAnimationFrame(capture.raf);capture=null}
const _paiReturnHome=returnHome;returnHome=function(){stopCapture();_paiReturnHome()};
